# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsEventMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=32, unique=True)),
                ('odds_event_id', models.CharField(max_length=64)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_checked_at'],
            },
        ),
    ]
