# Generated by Django 5.2.6 on 2025-09-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oddseventmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('game_id', models.CharField(max_length=32)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('commence_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-commence_time'],
            },
        ),
        migrations.CreateModel(
            name='DataRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markets_requested', models.TextField()),
                ('markets_found', models.IntegerField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('api_status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_logs', to='core.oddsevent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('market_key', models.CharField(max_length=50)),
                ('market_display', models.CharField(max_length=100)),
                ('over_odds', models.IntegerField(blank=True, null=True)),
                ('over_point', models.FloatField(blank=True, null=True)),
                ('under_odds', models.IntegerField(blank=True, null=True)),
                ('under_point', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='core.oddsevent')),
            ],
            options={
                'ordering': ['market_key', 'player_name'],
                'unique_together': {('event', 'player_name', 'market_key')},
            },
        ),
        migrations.CreateModel(
            name='PropLineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_odds', models.IntegerField(blank=True, null=True)),
                ('over_point', models.FloatField(blank=True, null=True)),
                ('under_odds', models.IntegerField(blank=True, null=True)),
                ('under_point', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_history', to='core.playerprop')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
