# Generated by Django 5.2.6 on 2025-09-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_oddsevent_datarefreshlog_playerprop_proplinehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_value', models.FloatField()),
                ('outcome', models.CharField(choices=[('over', 'Over'), ('under', 'Under'), ('push', 'Push'), ('void', 'Void')], max_length=10)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-graded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='proplinehistory',
            options={'ordering': ['-captured_at']},
        ),
        migrations.RenameField(
            model_name='proplinehistory',
            old_name='timestamp',
            new_name='captured_at',
        ),
        migrations.RemoveField(
            model_name='proplinehistory',
            name='over_point',
        ),
        migrations.RemoveField(
            model_name='proplinehistory',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='proplinehistory',
            name='under_point',
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='game_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='line_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='market_key',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='player_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='source',
            field=models.CharField(default='prizepicks', max_length=50),
        ),
        migrations.AddIndex(
            model_name='proplinehistory',
            index=models.Index(fields=['game_id', 'player_name', 'market_key'], name='core_propli_game_id_98fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='proplinehistory',
            index=models.Index(fields=['captured_at'], name='core_propli_capture_c6ee85_idx'),
        ),
        migrations.AddField(
            model_name='propgrade',
            name='proplinehistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.proplinehistory'),
        ),
        migrations.AlterUniqueTogether(
            name='propgrade',
            unique_together={('proplinehistory',)},
        ),
    ]
