# Generated by Django 5.2.6 on 2025-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propgrade_alter_proplinehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kickoff_et',
            field=models.DateTimeField(blank=True, help_text='Game kickoff time in Eastern', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='kickoff_local',
            field=models.DateTimeField(blank=True, help_text='Game kickoff time in local stadium time', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='kickoff_utc',
            field=models.DateTimeField(blank=True, help_text='Game kickoff time in UTC', null=True),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='clv_vs_closing',
            field=models.FloatField(blank=True, help_text='CLV vs closing line', null=True),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='clv_vs_opening',
            field=models.FloatField(blank=True, help_text='CLV vs opening line', null=True),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='is_closing_line',
            field=models.BooleanField(default=False, help_text='Is this the closing line?'),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='is_opening_line',
            field=models.BooleanField(default=False, help_text='Is this the opening line?'),
        ),
        migrations.AddField(
            model_name='proplinehistory',
            name='is_our_capture',
            field=models.BooleanField(default=False, help_text='Is this our capture time?'),
        ),
    ]
