# Generated by Django 5.2.6 on 2025-09-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game_kickoff_et_game_kickoff_local_game_kickoff_utc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nflreadpy_name', models.CharField(max_length=100, unique=True)),
                ('prizepicks_name', models.CharField(max_length=100)),
                ('player_id', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(max_length=10)),
                ('current_team', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nflreadpy_name'],
                'indexes': [models.Index(fields=['nflreadpy_name'], name='core_player_nflread_6b474c_idx'), models.Index(fields=['prizepicks_name'], name='core_player_prizepi_350a69_idx'), models.Index(fields=['player_id'], name='core_player_player__c875f5_idx')],
            },
        ),
    ]
