# Generated by Django 5.2.6 on 2025-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_player_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='player_name',
            field=models.CharField(blank=True, help_text='Player name for easy reference', max_length=100),
        ),
    ]
