# Generated by Django 5.2.6 on 2025-09-20 19:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_player_name_to_playerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDefense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2025)])),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('passing_attempts_allowed', models.FloatField(default=0)),
                ('passing_yards_allowed', models.FloatField(default=0)),
                ('passing_tds_allowed', models.FloatField(default=0)),
                ('passing_interceptions_forced', models.FloatField(default=0)),
                ('sacks_made', models.FloatField(default=0)),
                ('passing_epa_allowed', models.FloatField(default=0)),
                ('rushing_yards_allowed', models.FloatField(default=0)),
                ('rushing_tds_allowed', models.FloatField(default=0)),
                ('tackles_for_loss', models.FloatField(default=0)),
                ('rushing_epa_allowed', models.FloatField(default=0)),
                ('receiving_yards_allowed', models.FloatField(default=0)),
                ('receiving_tds_allowed', models.FloatField(default=0)),
                ('targets_allowed', models.FloatField(default=0)),
                ('receiving_epa_allowed', models.FloatField(default=0)),
                ('passing_defense_rank', models.IntegerField(blank=True, null=True)),
                ('rushing_defense_rank', models.IntegerField(blank=True, null=True)),
                ('receiving_defense_rank', models.IntegerField(blank=True, null=True)),
                ('overall_defense_rank', models.IntegerField(blank=True, null=True)),
                ('avg_passing_yards_allowed', models.FloatField(default=0)),
                ('avg_rushing_yards_allowed', models.FloatField(default=0)),
                ('avg_receiving_yards_allowed', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_stats', to='core.team')),
            ],
            options={
                'ordering': ['season', 'week', 'team'],
                'unique_together': {('team', 'season', 'week')},
            },
        ),
    ]
