# Generated by Django 5.2.6 on 2025-09-20 22:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teamdefense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2025)])),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('passing_attempts', models.FloatField(default=0)),
                ('passing_yards', models.FloatField(default=0)),
                ('passing_tds', models.FloatField(default=0)),
                ('passing_interceptions', models.FloatField(default=0)),
                ('sacks_taken', models.FloatField(default=0)),
                ('passing_epa', models.FloatField(default=0)),
                ('rushing_yards', models.FloatField(default=0)),
                ('rushing_tds', models.FloatField(default=0)),
                ('rushing_epa', models.FloatField(default=0)),
                ('receiving_yards', models.FloatField(default=0)),
                ('receiving_tds', models.FloatField(default=0)),
                ('targets', models.FloatField(default=0)),
                ('receiving_epa', models.FloatField(default=0)),
                ('passing_offense_rank', models.IntegerField(blank=True, null=True)),
                ('rushing_offense_rank', models.IntegerField(blank=True, null=True)),
                ('receiving_offense_rank', models.IntegerField(blank=True, null=True)),
                ('overall_offense_rank', models.IntegerField(blank=True, null=True)),
                ('avg_passing_yards', models.FloatField(default=0)),
                ('avg_rushing_yards', models.FloatField(default=0)),
                ('avg_receiving_yards', models.FloatField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offense_stats', to='core.team')),
            ],
            options={
                'ordering': ['team', 'season', 'week'],
                'unique_together': {('team', 'season', 'week')},
            },
        ),
    ]
