# Generated by Django 5.2.6 on 2025-09-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_team_offense'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='defense_pct',
            field=models.FloatField(blank=True, help_text='Percentage of defensive snaps played', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='defense_snaps',
            field=models.IntegerField(default=0, help_text='Number of defensive snaps played'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='offense_pct',
            field=models.FloatField(blank=True, help_text='Percentage of offensive snaps played', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='offense_snaps',
            field=models.IntegerField(default=0, help_text='Number of offensive snaps played'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='st_pct',
            field=models.FloatField(blank=True, help_text='Percentage of special teams snaps played', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='st_snaps',
            field=models.IntegerField(default=0, help_text='Number of special teams snaps played'),
        ),
    ]
