# Generated by Django 5.2.6 on 2025-09-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_snap_count_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='offense_snaps',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='offense_pct',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='defense_snaps',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='defense_pct',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='st_snaps',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='st_pct',
        ),
    ]
