# Generated by Django 5.2.6 on 2025-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_snap_count_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='aggressiveness',
            field=models.FloatField(blank=True, help_text='Aggressiveness percentage', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_air_yards_differential',
            field=models.FloatField(blank=True, help_text='Air yards differential', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_completed_air_yards',
            field=models.FloatField(blank=True, help_text='Average completed air yards', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_cushion',
            field=models.FloatField(blank=True, help_text='Average cushion at snap', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_expected_yac',
            field=models.FloatField(blank=True, help_text='Average expected YAC', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_intended_air_yards',
            field=models.FloatField(blank=True, help_text='Average intended air yards', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_separation',
            field=models.FloatField(blank=True, help_text='Average separation at catch', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_time_to_los',
            field=models.FloatField(blank=True, help_text='Average time to line of scrimmage', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_time_to_throw',
            field=models.FloatField(blank=True, help_text='Average time to throw in seconds', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='avg_yac_above_expectation',
            field=models.FloatField(blank=True, help_text='YAC above expectation', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='completion_percentage_above_expectation',
            field=models.FloatField(blank=True, help_text='Completion % above expectation', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='efficiency',
            field=models.FloatField(blank=True, help_text='Rushing efficiency', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='expected_rush_yards',
            field=models.FloatField(blank=True, help_text='Expected rush yards', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='rush_yards_over_expected',
            field=models.FloatField(blank=True, help_text='Rush yards over expected', null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='rush_yards_over_expected_per_att',
            field=models.FloatField(blank=True, help_text='Rush yards over expected per attempt', null=True),
        ),
    ]
